import { makeStore } from "@shared/util-client";
import { addToStore } from "./store";
import { st as shared } from "@shared/data-access";
import { st as platform } from "@platform/data-access";
import { st as social } from "@social/data-access";
import { st as decentverse } from "@decentverse/data-access";
export const st = makeStore(addToStore);
Object.assign(shared, st);
Object.assign(platform, st);
Object.assign(social, st);
Object.assign(decentverse, st);
export * as store from "./store";
export * as slice from "./slice";
export * as gql from "./gql";
export * from "./useLocale";
