export { slice as shared } from "@shared/data-access";
export { slice as social } from "@social/data-access";
export { slice as platform } from "@platform/data-access";
export { slice as decentverse } from "@decentverse/data-access";
export * from "./mocWallet/mocWallet.slice";
export * from "./mocSurvey/mocSurvey.slice";
export * from "./stakePool/stakePool.slice";
export * from "./advertise/advertise.slice";
export * from "./building/building.slice";
export * from "./user/user.slice";
