export { gql as shared } from "@shared/module";
export { gql as social } from "@social/module";
export { gql as platform } from "@platform/module";
export { gql as decentverse } from "@decentverse/module";
// export * from "./_scalar";
export * from "./mocWallet/mocWallet.gql";
export * from "./mocSurvey/mocSurvey.gql";
export * from "./user/user.gql";
export * from "./summary/summary.gql";
export * from "./stakePool/stakePool.gql";
export * from "./advertise/advertise.gql";
