import { lazy } from "@util/client";
import dynamic from "next/dynamic";
export const DataListContainer = dynamic(() => import("./DataListContainer").then((mod) => mod.DataListContainer));
export const DataTableList = dynamic(() => import("./DataListContainer").then((mod) => mod.DataTableList));
export const DataCardList = dynamic(() => import("./DataListContainer").then((mod) => mod.DataCardList));
export const DataEditModal = dynamic(() => import("./DataEditModal"));
export const RoleTags = dynamic(() => import("./DataColumn").then((mod) => mod.RoleTags));
export const StatusTag = dynamic(() => import("./DataColumn").then((mod) => mod.StatusTag));
export const DataItem = dynamic(() => import("./DataItem").then((mod) => mod.DataItem));
export const DataHandleAction = dynamic(() => import("./DataHandleAction").then((mod) => mod.DataHandleAction));
export const DataViewModal = dynamic(() => import("./DataViewModal").then((mod) => mod.DataViewModal));
export const DataDashboard = dynamic(() => import("./DataDashboard").then((mod) => mod.DataDashboard));
export const Property = dynamic(() => import("./Property").then((mod) => mod.Property));
export const AdminLayout = dynamic(() => import("./AdminLayout").then((mod) => mod.AdminLayout), { ssr: false });
export const DataPagination = dynamic(() => import("./DataList").then((mod) => mod.DataPagination));
export const DataSearch = dynamic(() => import("./DataList").then((mod) => mod.DataSearch));
export const SpringModal = dynamic(() => import("./SpringModal").then((mod) => mod.SpringModal));
export const LoadPagination = lazy(() => import("./LoadPagination"));
export const LoadUnits = lazy(() => import("./LoadUnits"));
export const LoadView = lazy(() => import("./LoadView"));
