/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721AMock,
  IERC721AMockInterface,
} from "../../../../contracts/mocks/ERC721ReceiverMock.sol/IERC721AMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721AMock__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721AMockInterface {
    return new utils.Interface(_abi) as IERC721AMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721AMock {
    return new Contract(address, _abi, signerOrProvider) as IERC721AMock;
  }
}
