/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as akamirCollectionSol from "./AkamirCollection.sol";
export type { akamirCollectionSol };
import type * as akamirFractionSol from "./AkamirFraction.sol";
export type { akamirFractionSol };
import type * as erc1155Sol from "./ERC1155.sol";
export type { erc1155Sol };
import type * as vaultFactorySol from "./VaultFactory.sol";
export type { vaultFactorySol };
import type * as extensions from "./extensions";
export type { extensions };
import type * as mocks from "./mocks";
export type { mocks };
export type { AKATransfer } from "./AKATransfer";
export type { AkaMarket } from "./AkaMarket";
export type { AkaToken } from "./AkaToken";
export type { Akamir } from "./Akamir";
export type { AkamirGenesis } from "./AkamirGenesis";
export type { ERC721A } from "./ERC721A";
export type { Multicall } from "./Multicall";
