/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721ReceiverMockSol from "./ERC721ReceiverMock.sol";
export type { erc721ReceiverMockSol };
export type { ERC4907AMock } from "./ERC4907AMock";
export type { ERC721ABurnableMock } from "./ERC721ABurnableMock";
export type { ERC721ABurnableStartTokenIdMock } from "./ERC721ABurnableStartTokenIdMock";
export type { ERC721AGasReporterMock } from "./ERC721AGasReporterMock";
export type { ERC721AMock } from "./ERC721AMock";
export type { ERC721AQueryableMock } from "./ERC721AQueryableMock";
export type { ERC721AQueryableStartTokenIdMock } from "./ERC721AQueryableStartTokenIdMock";
export type { ERC721AStartTokenIdMock } from "./ERC721AStartTokenIdMock";
export type { ERC721ATransferCounterMock } from "./ERC721ATransferCounterMock";
export type { ERC721AWithERC2309Mock } from "./ERC721AWithERC2309Mock";
export type { StartTokenIdHelper } from "./StartTokenIdHelper";
