/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISettings,
  ISettingsInterface,
} from "../../../contracts/VaultFactory.sol/ISettings";

const _abi = [
  {
    inputs: [],
    name: "feeReceiver",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISettings__factory {
  static readonly abi = _abi;
  static createInterface(): ISettingsInterface {
    return new utils.Interface(_abi) as ISettingsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISettings {
    return new Contract(address, _abi, signerOrProvider) as ISettings;
  }
}
