export { gql as shared } from "@shared/data-access";
export * from "./asset/asset.gql";
export * from "./callRoom/callRoom.gql";
export * from "./character/character.gql";
export * from "./dialog/dialog.gql";
export * from "./emoji/emoji.gql";
export * from "./game/game.gql";
export * from "./gossip/gossip.gql";
export * from "./live/live.gql";
export * from "./map/map.gql";
export * from "./role/role.gql";
export * from "./user/user.gql";
export * from "./webview/webview.gql";
export * from "./world/world.gql";
export * from "./_scalar";
