import { Store } from "@shared/util-client";
import { Texture, TextureLoader, Vector3 } from "three";
import type { RootState } from "./store";
import { defaultKeyboard } from "./_scalar";
export * as store from "./store";
export * as slice from "./slice";
export * as gql from "./gql";
export * from "./_hooks";
export * from "./useLocale";
export const st = {} as Store<RootState>;
export const loader = new TextureLoader();
loader.setCrossOrigin("anonymous");
